:Author: Robert Thas John
:Email:
:Date: 18/06/2022
:Revision: version#
:License: Public Domain

= Project: {Project}

Sample code for controlling a Grove relay from an Arduino Nano RP2040 Connect using both WIFI and a tactile button

== Step 1: Installation
This code requires that your device is registered with the Arduino IoT Cloud. Please follow my instructions on hackster.io to get started.
https://www.hackster.io/robert-thas/internet-controlled-light-switch-c4381e


== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 remote_lights_jun18a                => Arduino sketch folder
  ├── remote_lights_jun18a.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.
 

=== BOM
This is available from the Hackster project page.
https://www.hackster.io/robert-thas/internet-controlled-light-switch-c4381e


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
