#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Lights"
  https://create.arduino.cc/cloud/things/cceaba7b-304f-40de-8337-2721ac0932b1 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool lights;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

#include <Bounce2.h>

const int pin = 2; //the relay
const int button = 10; //the button to toggle lights

Bounce bouncer = Bounce(); //debouncing to handle button press variability

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  pinMode(pin, OUTPUT); //control the relay
  pinMode(button, INPUT_PULLUP); //read button presses
  bouncer.attach(button); //debounce
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  bouncer.update();
  //only process button presses once
  if (bouncer.changed() && bouncer.read() == LOW) {
    lights = !lights; //toggle the state of lights
    Serial.println(lights); //debug output
  }
  digitalWrite(pin, lights); //set the relay state
}

/*
  Since Lights is READ_WRITE variable, onLightsChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLightsChange()  {
  // Add your code here to act upon Lights change
  
}

