// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onLightsChange();

bool lights;

void initProperties(){

  ArduinoCloud.addProperty(lights, READWRITE, ON_CHANGE, onLightsChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
